global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'ansible'
    static_configs:
    - targets: ['192.168.99.99:9100']

  - job_name: 'web-server'
    static_configs:
    - targets: ['192.168.99.100:9100']

  - job_name: 'db-server'
    static_configs:
    - targets: ['192.168.99.101:9100']
    
  - job_name: 'kafka-exporter'
    static_configs:
    - targets: ['192.168.99.102:9308']

  - job_name: 'docker-host'
    static_configs:
    - targets: ['192.168.99.102:9100']